### ISSUE TITLE
Fails to load libTopologicCore.0.0.0.dylib on MacOS

### ISSUE THREAD

**Issue by p3palazzo** [wassimj/TopologicSverchok#25]
Latest MacOS release (2022-03-07) + Blender 3.0

On trying to activate I get the following error:

```
Traceback (most recent call last):
  File "/Applications/Blender 3.0.1.app/Contents/Resources/3.0/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/palazzo/Library/Application Support/Blender/3.0/scripts/addons/topologicsverchok/__init__.py", line 56, in <module>
    import topologic
ImportError: dlopen(/Users/palazzo/Library/Application Support/Blender/3.0/scripts/addons/topologicsverchok/site-packages/topologic/topologic.cpython-39-darwin.so, 0x0002): Library not loaded: libTopologicCore.0.0.0.dylib
  Referenced from: /Users/palazzo/Library/Application Support/Blender/3.0/scripts/addons/topologicsverchok/site-packages/topologic/topologic.cpython-39-darwin.so
  Reason: tried: 'libTopologicCore.0.0.0.dylib' (relative path not allowed in hardened program), '/usr/lib/libTopologicCore.0.0.0.dylib' (no such file)
```

**Comment by wassimj** [comment]
Sadly I don’t have a Mac to test. As a possible workaround try copying the libTopologicCore.0.0.0.dylib out of the add-ons folder into /usr/lib

**Comment by p3palazzo** [comment]
Thanks. Putting anything in the `/usr/lib` directory on a Mac requires disabling System Integrity Protection, which is very not good practice. I am trying a build from source using the Topologic repo and will let you know if it works.

**Comment by mdjska** [comment]
Hi, did you succeed with building it from source? I tried but got `ld: symbol(s) not found for architecture x86_64` error. But I also tried to build it using open cascade 7.5.1, which I later read is not supported?

**Comment by p3palazzo** [comment]
I have not had the time to look into this for the past several months, but last I tried I was stumbling on getting the proper versions of some of the requirements needed to build TopologicSverchok. Might try again later this year.
