### ISSUE TITLE
Error with latest Sverchok

### ISSUE THREAD

**Issue by Sinasta** [wassimj/TopologicSverchok#33]
Hi, i just want to report that there is an error because of the latest changes to Sverchok:

Traceback (most recent call last):
  File "/usr/share/blender/3.3/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/home/sinasta/.config/blender/3.3/scripts/addons/TopologicSverchok-main/__init__.py", line 418, in <module>
    imported_modules = make_node_list()
  File "/home/sinasta/.config/blender/3.3/scripts/addons/TopologicSverchok-main/__init__.py", line 413, in make_node_list
    module = importlib.import_module(f".{module_name}", base_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/sinasta/.config/blender/3.3/scripts/addons/TopologicSverchok-main/nodes/Topologic/GraphExportToDGCNN.py", line 5, in <module>
    from sverchok.core.socket_data import SvGetSocketInfo
ImportError: cannot import name 'SvGetSocketInfo' from 'sverchok.core.socket_data' (/home/sinasta/.config/blender/3.3/scripts/addons/sverchok-master/core/socket_data.py)

the error is most lkely caused by the changes introduced to Sverchok in this [commit](https://github.com/nortikin/sverchok/commit/ed954eb8a967a8a77cd5ef9bab5965ddc724ada0)

**Comment by Sinasta** [comment]
After deleting line 5 in GraphExportToDGCNN.py there is a new error:

Traceback (most recent call last):
  File "/usr/share/blender/3.3/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/home/sinasta/.config/blender/3.3/scripts/addons/TopologicSverchok-main/__init__.py", line 418, in <module>
    imported_modules = make_node_list()
  File "/home/sinasta/.config/blender/3.3/scripts/addons/TopologicSverchok-main/__init__.py", line 413, in make_node_list
    module = importlib.import_module(f".{module_name}", base_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/sinasta/.config/blender/3.3/scripts/addons/TopologicSverchok-main/nodes/Topologic/Run.py", line 5, in <module>
    from sverchok.core.update_system import make_tree_from_nodes, do_update
ImportError: cannot import name 'make_tree_from_nodes' from 'sverchok.core.update_system' (/home/sinasta/.config/blender/3.3/scripts/addons/sverchok-master/core/update_system.py)

**Comment by Sinasta** [comment]
which is probably caused by the same recent changements in Sverchok

**Comment by brunoperdigao** [comment]
I am having the same issue.

**Comment by wassimj** [comment]
Does this prevent TopologicSverchok from running altogether or just that particular node?

**Comment by brunoperdigao** [comment]
In my case, altogether. It prevents from enabling it when I click the checkbox in Blender Preferences

**Comment by wassimj** [comment]
A workaround until I get a chance to fix it is to comment out all occurrences of the offending node name in the top __init__.py file of TopologicSverchok

**Comment by wassimj** [comment]
I can confirm that Topologic is no longer compatible with the newest version of sverchok. I have raised an issue with the sverchok team to get help: [https://github.com/nortikin/sverchok/issues/4527](https://github.com/nortikin/sverchok/issues/4527)

**Comment by wassimj** [comment]
Please test the new v.0.8.1.7 alpha release to see if it solves these issues.

**Comment by wassimj** [comment]
Hi @Sinasta 
Great! Yes. Homemaker and Topologic have a circular dependency. We need to resolve this. The workaround is to install and activate Topologic then install and activate homemaker then restart. I think then the homemaker nodes in Topologic will appear.
Yes once topologic is pip installable, I will take it out of sverchok and treat it just like other python libraries.
