### ISSUE TITLE
Activation in Blender not working

### ISSUE THREAD

**Issue by TZwielehner** [wassimj/TopologicSverchok#36]
Topologic cannot be activated because of missing honeybee module. Can this dependency be installed automatically?

**Comment by wassimj** [comment]
Please install the latest alpha pre-release. You need Homemaker for it to be installed. All other python libraries can be installed through the Topologic.InstallDependencies node in Utilities. Restart Blender after you run it

**Comment by TZwielehner** [comment]
Homemaker is installed now. If I try to activate first it gives me the following error:
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\homemaker-addon-2022-05-14\__init__.py", line 10, in <module>
    from molior import Molior
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\homemaker-addon-2022-05-14\molior\__init__.py", line 45, in <module>
    from molior.style import Style
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\homemaker-addon-2022-05-14\molior\style\__init__.py", line 20, in <module>
    import os, yaml, copy, json
ModuleNotFoundError: No module named 'yaml'
```



If I activate Topologic first I get this error:
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\topologicsverchok\__init__.py", line 460, in <module>
    imported_modules = make_node_list()
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\topologicsverchok\__init__.py", line 455, in make_node_list
    module = importlib.import_module(f".{module_name}", base_name)
  File "C:\Users\...\AppData\Local\Programs\Python\Python39\Lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\topologicsverchok\nodes\Topologic\Run.py", line 6, in <module>
    from sverchok.core.update_system import UpdateTree
ImportError: cannot import name 'UpdateTree' from 'sverchok.core.update_system' (C:\Users\ZWT\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\sverchok-master\core\update_system.py)
```

**Comment by wassimj** [comment]
Ah, you have an outdated version of sverchok. Delete it, then go to the sverchok GitHub page. Do NOT download a release. Instead click on the GREEN “Code” button at the top right of the GitHub code page and download as ZIP. Install that ZIP file in Blender

**Comment by brunopostle** [comment]
On Mon, 20 Jun 2022, 12:40 TZwielehner, wrote:

>     import os, yaml, copy, json
> ModuleNotFoundError: No module named 'yaml
>
>
>
You need the 'noarch' Homemaker add-on from the Releases page, if you
download the source from git it doesn't have this module.

>

**Comment by TZwielehner** [comment]
Works now. Thank for your help!

**Comment by TZwielehner** [comment]
After a crash I get a new error, even after reinstalling the two plugins (same error regardless which one I activate first):
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\homemaker\__init__.py", line 9, in <module>
    from topologic import Vertex, Face, CellComplex
ImportError: cannot import name 'Vertex' from 'topologic' (unknown location)
```

**Comment by wassimj** [comment]
This usually happens when there are two conflicting libraries. I need more information on what is installed. Mainly, please use the homemaker no-arch plug-in with Topologic

**Comment by brunopostle** [comment]
You could install the Windows release of the Homemaker-addon (
blender-homemaker-2022-05-14-win.zip
<https://github.com/brunopostle/homemaker-addon/releases/download/2022-05-14/blender-homemaker-2022-05-14-win.zip>
), this currently has the same set of Topologic libraries as
Topologic-Sverchok, so it should be possible to have them both installed in
parallel without any conflict.

**Comment by TZwielehner** [comment]
Reinstalled everything. It works again now. I will keep an eye on this.
