### ISSUE TITLE
installating TopologicSverchok on Blender for Mac

### ISSUE THREAD

**Issue by sergicera** [wassimj/TopologicSverchok#54]
Hi !
I'm trying to install TopologicSverchok on Mac. 
On import, file __init__.py can't fint topologic, here is the console error :

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.4/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Users/sce/Library/Application Support/Blender/3.4/scripts/addons/TopologicSverchok-main/__init__.py", line 49, in <module>
    from topologic import Vertex, Edge, Wire, Face, Shell, Cell, CellComplex, Cluster, Topology
ImportError: cannot import name 'Vertex' from 'topologic' (unknown location)

**Comment by wassimj** [comment]
My apologies. TopologicSverchok does not support MacOS. We are looking into supporting that in the future, but we don’t have a timeline.

**Comment by sergicera** [comment]
Thanks for the update; I'll then proceed installing TopologicSverchok on a PC.
