### ISSUE TITLE
Cannot import 'Vertex' from Topologic

### ISSUE THREAD

**Issue by djsiete** [wassimj/TopologicSverchok#58]
I get the following error when I try to install Topologic to Sverchok:

Report:
Error
* Traceback (most recent call last):
File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 376, in enable
mod = importlib.import_module(module_name)
^^^^^^^^^^^^^^^
File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
return_bootstrap._gcd_import(name[level:], package, level)
ΑΑΑΑΑΑΑΑΑΑΑΑΑΑ
L^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\TopologicSverchok-main\__init__.py", line 49, in <module>
from topologic import Vertex, Edge, Wire, Face, Shell, Cell, CellComplex, Cluster, Topology
ImportError: cannot import name 'Vertex' from 'topologic' (unknown location)

**Comment by wassimj** [comment]
Sverchok and by association TopologicSverchok are not compatible with Blender 4.1

**Comment by nortikin** [comment]
> Sverchok and by association TopologicSverchok are not compatible with Blender 4.1

Sverchok now run under Blender 4+

**Comment by ValentinaPalazzolo** [comment]
I had the same issue with Blender 4.2.1

**Comment by ppaawweeuu** [comment]
same issue with blender 4.3.2

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.3\4.3\scripts\modules\addon_utils.py", line 428, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.3\4.3\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\pawel.czernecki\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\topologicsverchok\__init__.py", line 49, in <module>
    from topologic import Vertex, Edge, Wire, Face, Shell, Cell, CellComplex, Cluster, Topology
ImportError: cannot import name 'Vertex' from 'topologic' (unknown location)
```

**Comment by faridcher** [comment]
`topologic` python package is changed to `topologicpy` and this plugin imports the old `topologic` python package and hence the error occurs.

**Comment by nortikin** [comment]
can we fix?
Sverchok run on 3.6, 4.5, 5.1 blender. Even on 2.78

**Comment by wassimj** [comment]
Apologies everyone. TopologicSverchok is obsolete. However, there is an internal version that has been written from the ground up. Release date is uncertain. For now, you can use topologicpy via custom python nodes.
